# Generated by Django 3.0.7 on 2020-07-21 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='Documents')),
                ('color', models.CharField(choices=[('Black and White - Kshs 5', 'Black and White - Kshs 5'), ('Colored - Kshs 10', 'Colored - Kshs 10')], max_length=100)),
                ('extra', models.CharField(choices=[('Stapled - Kshs 0', 'Stapled - Kshs 0'), ('Hard Cover - Kshs 50', 'Hard Cover - Kshs 50'), ('Spiral Binding - Kshs 30', 'Spiral Binding - Kshs 30')], max_length=100)),
                ('pages', models.CharField(max_length=1000)),
                ('copies', models.CharField(max_length=1000)),
                ('building', models.CharField(default='', max_length=500)),
                ('office', models.CharField(default='', max_length=50)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
