# Generated by Django 3.0.7 on 2020-07-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0009_auto_20200729_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('5', '5'), ('10', '10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='extra',
            field=models.CharField(choices=[('0', '0'), ('50', '50'), ('30', '30')], max_length=100),
        ),
    ]
