# Generated by Django 3.0.7 on 2020-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0010_auto_20200730_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('Black (Kshs 5)', '5'), ('Colored (Kshs 10)', '10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='extra',
            field=models.CharField(choices=[('Stapled (Kshs 0)', '0'), ('HardCover (Kshs 50)', '50'), ('Spiral Bind (Kshs 30)', '30')], max_length=100),
        ),
    ]
