# Generated by Django 3.0.7 on 2020-07-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0011_auto_20200730_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extra',
            field=models.CharField(choices=[('0', 'Stapled (Kshs 0)'), ('50', 'HardCover (Kshs 50)'), ('30', 'Spiral Bind (Kshs 30)')], max_length=100),
        ),
    ]
