# Generated by Django 3.0.7 on 2020-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0014_auto_20200731_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(choices=[('5', '5'), ('10', '10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='extra',
            field=models.CharField(choices=[('o', '0'), ('50', '50'), ('30', '30')], max_length=100),
        ),
    ]
