# Generated by Django 3.0.7 on 2020-08-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0015_auto_20200801_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
