# Generated by Django 3.0.7 on 2020-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0016_document_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='Documents/%Y/%m/%d'),
        ),
    ]
