# Generated by Django 3.0.7 on 2020-08-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0017_auto_20200801_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extra',
            field=models.CharField(choices=[('0', '0'), ('50', '50'), ('30', '30')], max_length=100),
        ),
    ]
