# Generated by Django 3.0.7 on 2020-08-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0019_auto_20200801_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extra',
        ),
        migrations.AddField(
            model_name='document',
            name='bind',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
